apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bluesky

resources:
  - pv.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml

labels:
  - pairs:
      app: kafka
      component: messaging

buildMetadata: [managedByLabel]