apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bluesky

resources:
  - configmap.yaml
  - statefulset.yaml
  - service.yaml

commonLabels:
  app: redpanda
  component: messaging

commonAnnotations:
  app.kubernetes.io/part-of: bluesky-consumer
  app.kubernetes.io/managed-by: argocd