apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bluesky

resources:
  - sealed-secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - hpa.yaml

commonLabels:
  app: storage-worker
  component: worker

commonAnnotations:
  app.kubernetes.io/part-of: bluesky-consumer
  app.kubernetes.io/managed-by: argocd