apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bluesky

resources:
  - sealed-secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - hpa.yaml

labels:
  - pairs:
      app: storage-worker
      component: worker

buildMetadata: [managedByLabel]