---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-credentials
  namespace: bluesky
spec:
  encryptedData:
    access-key-id: AgBkMBhfmpHvyJuCwweHj4x4J3ZB5VzxIL0QVHIvvdwnpkhNFg9tpkgLDYuJpCyi5gFFgu3i3QD/RCM6o5VWNSg4wgFOU9uZSy7qB5Gch8C9iPuw+CzjUY3WjE+hrY0Irgdvsxzarp/BYz+8XaRLq/GRbqDwiLZuolyEhNWYP8R5CT7ZjXDTRUsomICWuTTLz0Aq9SiwPQqxqv6RVegbRarrlMp4ZtoQVZFZ9OzzwqKlkxU1NWSs708JLdAuKgfy+bDOAHSQ/ihzLsHvGbNhX6SVMY8nrfjo1k+EtF2lV7BSEsdpBRTH4V/OGxPz/QnXC9STjGJCreK8Dp4Jquve8Q98VS/d5IvClxGSbDzv7h6qAMhRb6fqhIYmEa7cbcxP6F1dk861fAzjdGgIigxPWfLPPVRdfcxUckyc7mmnE3fL5TsmRtQbLm7tHDb1npyfln55fq87CLj3F5ZCjUnaSJp4KL0lK2fXUu4iS3zISa0ZloAPUkAwdiNHtDA51nLMGHaZLPbvMleNJTRzeyqxXrqwT+rg8OGZhdtV9rcvXpEfkvxMm4AFqEfIBM9C8ezycw9KzWwzPPZa5rrTx/yQtNOorhsaQWbNLO8gaQTMj+dR5O7S5ifiELzAcUrRA6+qiRqnDm98OgA/hWXpE5CSNgtfVXZCcWAIj7NTkrk3KGT7eK0I9tlBPODvxso1i9uggvuw3rJjm/dSShhm
    secret-access-key: AgCdMru8bcWwqJfu7Rtgu1IJ4eFwD1d/kb+kyGnMiwTV/fJWfF0nll++TY4aY69k9NfXT1GiWxD7gsxpIcXWkEqqYdQFeLrV6Kq2gPWAY0ONajQ+Vr2NiNL64YKi6eOhjF1EJPMi1okzsyt2pfst+ulQuT3LhfHeohnnopB4FmSUewXxoqFAyL1ISf89BvH1pE8/jLp6/aS3BTPo6YAIkdL/WV4xF/GLFGnTlw790N7unMmzRi339PitTJ8p+tbYX499H3pQ9gh64Bx8jX0sZRC+yPNpD45dEPitVpA0PM1VdJCVbMwRYCGAF8orxth4Ev6bGZHEq7VUMEGMdwGrnkRxSZTPcwUmc7lJLaF63XPSMwJbA6wx8KIr1Tnniu9j0q5gp+04PVvXP8Irntbc06Qy/BJAeRbnK4fboT16ALjL48M1Y73J45ld4e0KWJx4Ge6M3WgNguIoey3NSoePPSPaZmp9m/FJh8U/khQVPqND0aeduEfSyqFxKIJhzyycMeWYu3v97yaJOP7p8sIKAQgCe+ZvD/Pq/DP3dpLoRz3jVrz57BovvV4iql5ho5DKhA38bsOgZ40Rfeqcyg28YtdGKpHbygIdn6sVfugoLGOVq27000g55xiFJoevTkYLo3oKDlf9thfRxLpj617MUhyHS4qDcmsiSBKwKQ574noiJ1Gyuc9DZet7oAemN+Y80v+NqpT2IuRDYQ==
  template:
    metadata:
      name: s3-credentials
      namespace: bluesky
