apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: storage-worker
  namespace: bluesky
  labels:
    app: storage-worker
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app: storage-worker
  endpoints:
  - port: http
    path: /metrics
    interval: 30s