apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bluesky

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

commonLabels:
  app: firehose-consumer
  component: consumer

commonAnnotations:
  app.kubernetes.io/part-of: bluesky-consumer
  app.kubernetes.io/managed-by: argocd